# Generated by Django 4.1.3 on 2022-11-22 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=15, verbose_name='cpf')),
                ('categoria', models.CharField(choices=[('moto', 'moto'), ('carro', 'carro'), ('caminhao', 'caminhão'), ('carreta', 'carreta')], max_length=10, verbose_name='veiculo')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nome')),
            ],
        ),
    ]
