# Generated by Django 4.1.3 on 2023-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='veículo',
            field=models.CharField(blank=True, choices=[('usuario', 'usuario'), ('colaborador', 'colaborador')], max_length=20, null=True, verbose_name='veículo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('moto', 'moto'), ('carro', 'carro'), ('caminhão', 'caminhão'), ('carreta', 'carreta')], default='usuario', max_length=20, verbose_name='tipo_de_usuario'),
        ),
    ]
