# Generated by Django 4.1.3 on 2023-02-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_veículo_alter_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'usuario'), ('colaborador', 'colaborador')], default='usuario', max_length=20, verbose_name='tipo_de_usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='veículo',
            field=models.CharField(blank=True, choices=[('moto', 'moto'), ('carro', 'carro'), ('caminhão', 'caminhão'), ('carreta', 'carreta')], default=1, max_length=20, verbose_name='veículo'),
            preserve_default=False,
        ),
    ]
