# Generated by Django 4.1.3 on 2022-11-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=12)),
                ('coleta', models.CharField(max_length=100)),
                ('entrega', models.CharField(max_length=100)),
                ('percurso', models.IntegerField()),
                ('veículo', models.CharField(choices=[(1, 'Moto'), (2, 'carro'), (3, 'caminhão'), (4, 'carreta')], max_length=10)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
    ]
