# Generated by Django 4.1.3 on 2022-11-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0002_serviço_delete_servidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviço',
            name='servico',
        ),
    ]
