# Generated by Django 4.1.3 on 2022-11-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0003_remove_serviço_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviço',
            name='servicos',
            field=models.CharField(choices=[(1, 'viagem'), (2, 'delivery')], max_length=12, null=True),
        ),
    ]
