# Generated by Django 4.1.3 on 2022-11-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0005_alter_serviço_servicos_alter_serviço_veículo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviço',
            name='percurso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serviço',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
