# Generated by Django 4.1.3 on 2022-11-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0006_alter_serviço_percurso_alter_serviço_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviço',
            name='percurso',
        ),
        migrations.RemoveField(
            model_name='serviço',
            name='valor',
        ),
    ]
