# Generated by Django 4.1.3 on 2022-11-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0007_remove_serviço_percurso_remove_serviço_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviço',
            name='coleta',
            field=models.CharField(max_length=100, verbose_name='coleta'),
        ),
        migrations.AlterField(
            model_name='serviço',
            name='entrega',
            field=models.CharField(max_length=100, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='serviço',
            name='servicos',
            field=models.IntegerField(choices=[(1, 'viagem'), (2, 'delivery')], null=True, verbose_name='servicos'),
        ),
        migrations.AlterField(
            model_name='serviço',
            name='veículo',
            field=models.IntegerField(choices=[(1, 'Moto'), (2, 'carro'), (3, 'caminhão'), (4, 'carreta')], verbose_name='veículo'),
        ),
    ]
