# Generated by Django 4.1.3 on 2022-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0009_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.IntegerField(choices=[(1, 'viagem'), (2, 'delivery')], null=True, verbose_name='servicos')),
                ('coleta', models.CharField(max_length=100, verbose_name='coleta')),
                ('entrega', models.CharField(max_length=100, verbose_name='entrega')),
                ('veículo', models.IntegerField(choices=[(1, 'Moto'), (2, 'carro'), (3, 'caminhão'), (4, 'carreta')], verbose_name='veículo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
        ),
        migrations.DeleteModel(
            name='Serviço',
        ),
    ]
