# Generated by Django 4.1.3 on 2022-11-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0010_servicos_delete_serviço'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='slug',
        ),
    ]
