# Generated by Django 4.1.3 on 2022-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0011_remove_servicos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='distancia',
            field=models.IntegerField(blank=True, null=True, verbose_name='distancia'),
        ),
    ]
