# Generated by Django 4.1.3 on 2022-11-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0012_servicos_distancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='veículo',
            new_name='veiculo',
        ),
    ]
