# Generated by Django 4.1.3 on 2022-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0013_rename_veículo_servicos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='coleta',
            field=models.CharField(max_length=100, null=True, verbose_name='coleta'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='entrega',
            field=models.CharField(max_length=100, null=True, verbose_name='entrega'),
        ),
    ]
