# Generated by Django 4.1.3 on 2022-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0014_alter_servicos_coleta_alter_servicos_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='distancia',
            field=models.IntegerField(null=True, verbose_name='distancia'),
        ),
    ]
