# Generated by Django 4.1.3 on 2022-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0017_alter_servicos_distancia_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='distancia',
            field=models.IntegerField(blank=True, verbose_name='distancia'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='veiculo',
            field=models.IntegerField(choices=[(1, 'Moto'), (2, 'carro'), (3, 'caminhão'), (4, 'carreta')], null=2, verbose_name='veículo'),
        ),
    ]
