# Generated by Django 4.1.3 on 2022-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0019_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='coleta',
            field=models.CharField(max_length=100, verbose_name='coleta'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='entrega',
            field=models.CharField(max_length=100, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='servicos',
            field=models.IntegerField(choices=[(1, 'viagem'), (2, 'delivery')], verbose_name='servicos'),
        ),
    ]
