# Generated by Django 4.1.3 on 2022-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0020_alter_servicos_coleta_alter_servicos_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='servicos',
            field=models.CharField(choices=[(1, 'viagem'), (2, 'delivery')], max_length=20, verbose_name='servicos'),
        ),
    ]
