# Generated by Django 4.1.3 on 2022-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0026_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='valor',
            field=models.IntegerField(blank=True, default=2, verbose_name='valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicos',
            name='veiculo',
            field=models.IntegerField(blank=True, choices=[(1, 'Moto'), (2, 'carro'), (3, 'caminhão'), (4, 'carreta')], verbose_name='veiculo'),
        ),
    ]
