# Generated by Django 4.1.3 on 2022-11-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0027_servicos_valor_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='distancia'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='valor'),
        ),
    ]
