# Generated by Django 4.1.3 on 2022-11-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0029_alter_servicos_distancia_alter_servicos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, verbose_name='distancia'),
        ),
    ]
