# Generated by Django 4.1.3 on 2022-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0030_alter_servicos_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='distancia'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, verbose_name='valor'),
        ),
    ]
