# Generated by Django 4.1.3 on 2022-11-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0034_alter_servicos_servicos_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='servicos',
            field=models.CharField(choices=[('1', 'viagem'), ('2', 'delivery')], max_length=10, verbose_name='servicos'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='veiculo',
            field=models.IntegerField(blank=True, choices=[(1, 'moto'), (2, 'carro'), (3, 'caminhão'), (4, 'carreta')], verbose_name='veiculo'),
        ),
    ]
