# Generated by Django 4.1.3 on 2022-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0035_alter_servicos_servicos_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='servicos',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default=1, max_length=15, verbose_name='status'),
            preserve_default=False,
        ),
    ]
