# Generated by Django 4.1.3 on 2022-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0037_alter_servicos_servicos_alter_servicos_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='time',
            field=models.CharField(default=1, max_length=20, verbose_name='time'),
            preserve_default=False,
        ),
    ]
