# Generated by Django 4.1.3 on 2022-11-21 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUber', '0039_alter_servicos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicos',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='time',
            field=models.CharField(blank=True, max_length=20, verbose_name='time'),
        ),
    ]
