# Generated by Django 4.1.3 on 2022-11-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0041_remove_servicos_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], max_length=15, null=True, verbose_name='status'),
        ),
    ]
