# Generated by Django 4.1.3 on 2023-02-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0044_sol_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol_servicos',
            name='valor',
            field=models.IntegerField(blank=True, verbose_name='valor'),
        ),
    ]
