# Generated by Django 4.1.3 on 2023-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUber', '0045_alter_sol_servicos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol_servicos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='valor'),
        ),
    ]
